# Generated by Django 5.2.1 on 2025-06-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfSmartcards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=100, unique=True)),
                ('subscriberCode', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100, unique=True)),
                ('pairedBox', models.CharField(max_length=100)),
                ('products', models.JSONField(blank=True, null=True)),
                ('packages', models.JSONField(blank=True, null=True)),
                ('packageNames', models.JSONField(blank=True, null=True)),
                ('regionId', models.IntegerField()),
                ('regionName', models.CharField(max_length=100)),
                ('masterSn', models.CharField(blank=True, max_length=100, null=True)),
                ('hcId', models.CharField(blank=True, max_length=100, null=True)),
                ('lastActivation', models.DateTimeField(blank=True, null=True)),
                ('lastContact', models.DateTimeField(blank=True, null=True)),
                ('lastServiceListDownload', models.DateTimeField(blank=True, null=True)),
                ('firmwareVersion', models.CharField(blank=True, max_length=100, null=True)),
                ('camlibVersion', models.CharField(blank=True, max_length=100, null=True)),
                ('blacklisted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('defect', models.BooleanField(default=False)),
                ('stbModel', models.CharField(blank=True, max_length=100, null=True)),
                ('stbVendor', models.CharField(blank=True, max_length=100, null=True)),
                ('stbChipset', models.CharField(blank=True, max_length=100, null=True)),
                ('mac', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListOfSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('lastName', models.CharField(blank=True, max_length=100, null=True)),
                ('firstName', models.CharField(blank=True, max_length=100, null=True)),
                ('smartcards', models.JSONField(blank=True, null=True)),
                ('hcId', models.CharField(max_length=100, unique=True)),
                ('hcName', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('created', models.DateField()),
                ('modified', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_code', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sn', models.CharField(blank=True, max_length=100, null=True)),
                ('pin', models.CharField(blank=True, max_length=100, null=True)),
                ('last_activation', models.DateTimeField(blank=True, null=True)),
                ('last_contact', models.DateTimeField(blank=True, null=True)),
                ('last_service_list_download', models.DateTimeField(blank=True, null=True)),
                ('products', models.JSONField(blank=True, null=True)),
                ('packages', models.JSONField(blank=True, null=True)),
                ('packageNames', models.JSONField(blank=True, null=True)),
                ('login1', models.IntegerField(blank=True, null=True)),
                ('login2', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('udid', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberLoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login1', models.IntegerField(blank=True, null=True)),
                ('login2', models.CharField(blank=True, max_length=100, null=True)),
                ('additionalLogins', models.JSONField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
