# Generated by Django 5.2.1 on 2025-06-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofsmartcards',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listofsmartcards',
            name='casIds',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listofsmartcards',
            name='configId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listofsmartcards',
            name='configProtected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listofsmartcards',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listofsmartcards',
            name='hardware',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listofsmartcards',
            name='lastApiKeyId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listofsmartcards',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listofsmartcards',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listofsmartcards',
            name='defect',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscriberinfo',
            name='udid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
