# Generated by Django 5.2.1 on 2025-06-05 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udid', '0002_listofsmartcards_alias_listofsmartcards_casids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberlogininfo',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_info', to='udid.listofsubscriber'),
        ),
        migrations.AlterField(
            model_name='listofsmartcards',
            name='blacklisted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='listofsmartcards',
            name='configProtected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='listofsmartcards',
            name='defect',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='listofsmartcards',
            name='disabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='listofsmartcards',
            name='firstName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listofsmartcards',
            name='lastName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listofsmartcards',
            name='pin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listofsmartcards',
            name='regionId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listofsmartcards',
            name='regionName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listofsubscriber',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listofsubscriber',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listofsubscriber',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listofsubscriber',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listofsubscriber',
            name='modified',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listofsubscriber',
            name='zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
