# Generated by Django 5.2.1 on 2025-06-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udid', '0003_subscriberlogininfo_subscriber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofsmartcards',
            name='sn',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='listofsmartcards',
            name='subscriberCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
