# Generated by Django 5.2.1 on 2025-06-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udid', '0004_alter_listofsmartcards_sn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofsmartcards',
            name='firstName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listofsmartcards',
            name='lastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listofsmartcards',
            name='pairedBox',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listofsmartcards',
            name='pin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
