# Generated by Django 5.2.1 on 2025-06-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udid', '0005_alter_listofsmartcards_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofsubscriber',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listofsubscriber',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
