# Generated by Django 5.2.1 on 2025-06-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udid', '0006_alter_listofsubscriber_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofsubscriber',
            name='id',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
    ]
