# Generated by Django 5.2.1 on 2025-06-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udid', '0007_alter_listofsubscriber_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofsubscriber',
            name='hcId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listofsubscriber',
            name='hcName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
