# Generated by Django 5.2.1 on 2025-06-13 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udid', '0008_alter_listofsubscriber_hcid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberinfo',
            name='activated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='listofsubscriber',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriberlogininfo',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_info', to='udid.listofsubscriber', to_field='code'),
        ),
    ]
