# Generated by Django 5.2.1 on 2025-06-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udid', '0009_subscriberinfo_activated_alter_listofsubscriber_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofsmartcards',
            name='lastActivationIP',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
