# Generated by Django 5.2.1 on 2025-06-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udid', '0010_listofsmartcards_lastactivationip'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberlogininfo',
            name='licenses',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
