# Generated by Django 5.2.1 on 2025-06-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udid', '0011_subscriberlogininfo_licenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriberlogininfo',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='subscriberlogininfo',
            name='subscriberCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
