# Generated by Django 5.2.1 on 2025-06-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udid', '0012_remove_subscriberlogininfo_subscriber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriberinfo',
            old_name='last_activation',
            new_name='lastActivation',
        ),
        migrations.RenameField(
            model_name='subscriberinfo',
            old_name='last_contact',
            new_name='lastContact',
        ),
        migrations.RenameField(
            model_name='subscriberinfo',
            old_name='last_service_list_download',
            new_name='lastServiceListDownload',
        ),
        migrations.AddField(
            model_name='subscriberinfo',
            name='lastActivationIP',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriberinfo',
            name='lastApiKeyId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriberinfo',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
