# Generated by Django 5.2.1 on 2025-06-20 13:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udid', '0013_rename_last_activation_subscriberinfo_lastactivation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('udid_generated', 'UDID Generated'), ('udid_validated', 'UDID Validated'), ('udid_used', 'UDID Used'), ('login_attempt', 'Login Attempt'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked')], max_length=20)),
                ('subscriber_code', models.CharField(blank=True, max_length=100, null=True)),
                ('udid', models.CharField(blank=True, max_length=100, null=True)),
                ('operator_id', models.CharField(blank=True, max_length=100, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UDIDAuthRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('subscriber_code', models.CharField(db_index=True, max_length=100)),
                ('temp_token', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('used', 'Used')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('validated_by_operator', models.CharField(blank=True, max_length=100, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('attempts_count', models.IntegerField(default=0)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscriberinfo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='subscriberinfo',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='subscriberinfo',
            name='udid',
        ),
        migrations.AddField(
            model_name='subscriberinfo',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriberinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriberinfo',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriberinfo',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriberinfo',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriberinfo',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriberinfo',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriberinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='listofsubscriber',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriberinfo',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='subscriberinfo',
            index=models.Index(fields=['subscriber_code'], name='udid_subscr_subscri_8551cc_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriberinfo',
            index=models.Index(fields=['sn'], name='udid_subscr_sn_074c32_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriberinfo',
            index=models.Index(fields=['activated'], name='udid_subscr_activat_006b44_idx'),
        ),
        migrations.AddIndex(
            model_name='authauditlog',
            index=models.Index(fields=['timestamp'], name='udid_authau_timesta_4f42ea_idx'),
        ),
        migrations.AddIndex(
            model_name='authauditlog',
            index=models.Index(fields=['subscriber_code'], name='udid_authau_subscri_4fb1f0_idx'),
        ),
        migrations.AddIndex(
            model_name='authauditlog',
            index=models.Index(fields=['action_type'], name='udid_authau_action__070b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='udidauthrequest',
            index=models.Index(fields=['udid', 'status'], name='udid_udidau_udid_21a057_idx'),
        ),
        migrations.AddIndex(
            model_name='udidauthrequest',
            index=models.Index(fields=['expires_at'], name='udid_udidau_expires_6d8c14_idx'),
        ),
        migrations.AddIndex(
            model_name='udidauthrequest',
            index=models.Index(fields=['subscriber_code'], name='udid_udidau_subscri_535f18_idx'),
        ),
    ]
