# Generated by Django 5.2.1 on 2025-06-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udid', '0015_udidauthrequest_sn'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='udidauthrequest',
            index=models.Index(fields=['sn'], name='udid_udidau_sn_bbd06f_idx'),
        ),
        migrations.AddIndex(
            model_name='udidauthrequest',
            index=models.Index(fields=['subscriber_code', 'sn'], name='udid_udidau_subscri_505e05_idx'),
        ),
        migrations.AddIndex(
            model_name='udidauthrequest',
            index=models.Index(fields=['status', 'expires_at'], name='udid_udidau_status_7ad707_idx'),
        ),
    ]
