# Generated by Django 5.2.1 on 2025-06-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udid', '0016_udidauthrequest_udid_udidau_sn_bbd06f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='udidauthrequest',
            name='lastActivation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='udidauthrequest',
            name='lastActivationIP',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='udidauthrequest',
            name='lastServiceListDownload',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
