# Generated by Django 5.2.1 on 2025-06-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udid', '0017_udidauthrequest_lastactivation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(choices=[('android_tv', 'Android TV'), ('samsung_tv', 'Samsung Smart TV'), ('lg_tv', 'LG Smart TV'), ('set_top_box', 'Set Top Box')], max_length=50, unique=True)),
                ('app_version', models.CharField(default='1.0', max_length=20)),
                ('private_key_pem', models.TextField()),
                ('public_key_pem', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['app_type', 'is_active'], name='udid_appcre_app_typ_f51c0a_idx')],
            },
        ),
    ]
