# Generated by Django 5.2.1 on 2025-06-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udid', '0018_appcredentials'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appcredentials',
            name='udid_appcre_app_typ_f51c0a_idx',
        ),
        migrations.AddField(
            model_name='udidauthrequest',
            name='app_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='udidauthrequest',
            name='app_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='udidauthrequest',
            name='encrypted_response_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appcredentials',
            name='app_version',
            field=models.CharField(db_index=True, default='1.0', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='appcredentials',
            unique_together={('app_type', 'app_version')},
        ),
        migrations.AddIndex(
            model_name='appcredentials',
            index=models.Index(fields=['app_type', 'app_version', 'is_active'], name='udid_appcre_app_typ_9e8651_idx'),
        ),
    ]
