# Generated by Django 5.2.1 on 2025-06-27 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udid', '0019_remove_appcredentials_udid_appcre_app_typ_f51c0a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedCredentialsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udid', models.CharField(db_index=True, max_length=100)),
                ('subscriber_code', models.CharField(db_index=True, max_length=100)),
                ('sn', models.CharField(blank=True, max_length=100, null=True)),
                ('app_type', models.CharField(max_length=50)),
                ('app_version', models.CharField(max_length=20)),
                ('encryption_algorithm', models.CharField(default='AES-256-CBC + RSA-OAEP', max_length=50)),
                ('encrypted_data_hash', models.CharField(max_length=64)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('delivered_successfully', models.BooleanField(default=False)),
                ('delivery_attempts', models.IntegerField(default=0)),
                ('last_delivery_error', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='appcredentials',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appcredentials',
            name='is_compromised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appcredentials',
            name='key_fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='appcredentials',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appcredentials',
            name='revocation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appcredentials',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appcredentials',
            name='revoked_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appcredentials',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='udidauthrequest',
            name='app_credentials_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='udid.appcredentials'),
        ),
        migrations.AddField(
            model_name='udidauthrequest',
            name='credentials_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='udidauthrequest',
            name='encryption_successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='udidauthrequest',
            name='requests_from_ip_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='udidauthrequest',
            name='suspicious_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appcredentials',
            name='app_type',
            field=models.CharField(choices=[('android_tv', 'Android TV'), ('samsung_tv', 'Samsung Smart TV'), ('lg_tv', 'LG Smart TV'), ('set_top_box', 'Set Top Box'), ('mobile_app', 'Mobile App'), ('web_player', 'Web Player')], max_length=50),
        ),
        migrations.AlterField(
            model_name='appcredentials',
            name='private_key_pem',
            field=models.TextField(help_text='Clave privada - NUNCA enviar al cliente'),
        ),
        migrations.AlterField(
            model_name='appcredentials',
            name='public_key_pem',
            field=models.TextField(help_text='Clave pública - se embebe en aplicaciones'),
        ),
        migrations.AddIndex(
            model_name='appcredentials',
            index=models.Index(fields=['is_active', 'expires_at'], name='udid_appcre_is_acti_8e6ced_idx'),
        ),
        migrations.AddIndex(
            model_name='appcredentials',
            index=models.Index(fields=['key_fingerprint'], name='udid_appcre_key_fin_ef1ca8_idx'),
        ),
        migrations.AddField(
            model_name='encryptedcredentialslog',
            name='app_credentials_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udid.appcredentials'),
        ),
        migrations.AddIndex(
            model_name='encryptedcredentialslog',
            index=models.Index(fields=['timestamp'], name='udid_encryp_timesta_c42613_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedcredentialslog',
            index=models.Index(fields=['subscriber_code', 'app_type'], name='udid_encryp_subscri_5fca8b_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedcredentialslog',
            index=models.Index(fields=['udid'], name='udid_encryp_udid_e2992c_idx'),
        ),
    ]
