# Generated by Django 5.2.1 on 2025-07-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udid', '0020_encryptedcredentialslog_appcredentials_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='udidauthrequest',
            name='method',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=20),
        ),
    ]
