# Generated by Django 5.2.1 on 2025-07-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udid', '0022_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='document_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
