# Generated by Django 5.2.1 on 2025-07-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udid', '0023_userprofile_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='document_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
