# Generated by Django 5.2.1 on 2025-08-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udid', '0024_alter_userprofile_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcredentials',
            name='app_type',
            field=models.CharField(choices=[('android_tv', 'Android TV'), ('android_mobile', 'Android Mobile'), ('10foot', '10 Foot UI'), ('set_top_box', 'Set Top Box'), ('ios_mobile', 'iOS Mobile'), ('ios_tv', 'Apple TV'), ('web_player', 'Web Player')], max_length=50),
        ),
    ]
